/** Released registries, captured from the named Git tags. A database may have
 * crossed several registries: Effect recorded only the new numeric suffix.
 * Keep these identities even when the corresponding carry files move. */
export const legacyMigrationHistories = [
  {
    source: "lastcode/build/v0.0.34-nightly.20260822.1160.1",
    entries: [
      [42, "ProjectionThreadAnnotation"],
      [43, "UpdateDrain"],
      [44, "UpdateDrainClaim"],
    ],
  },
  {
    source: "lastcode/build/v0.0.34-nightly.20260824.1174.2.1",
    entries: [
      [42, "ProjectionThreadAnnotation"],
      [43, "UpdateDrain"],
      [44, "UpdateDrainClaim"],
      [45, "ProjectionTurnRequestCorrelations"],
    ],
  },
  {
    source: "lastcode/build/v0.0.34-nightly.20260825.1180.1",
    entries: [
      [42, "ProjectionThreadAnnotation"],
      [43, "UpdateDrain"],
      [44, "UpdateDrainClaim"],
      [45, "ProjectionTurnRequestCorrelations"],
      [46, "ProjectionThreadWorktreeCleanup"],
    ],
  },
  {
    source: "lastcode/build/v0.0.34-nightly.20260825.1185.1.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadAnnotation"],
      [44, "UpdateDrain"],
      [45, "UpdateDrainClaim"],
      [46, "ProjectionTurnRequestCorrelations"],
      [47, "ProjectionThreadWorktreeCleanup"],
      [48, "ProjectionThreadLinkedPullRequest"],
    ],
  },
  {
    source: "lastcode/build/v0.0.35-nightly.20260827.1202.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ProjectionThreadAnnotation"],
      [45, "UpdateDrain"],
      [46, "UpdateDrainClaim"],
      [47, "ProjectionTurnRequestCorrelations"],
      [48, "ProjectionThreadWorktreeCleanup"],
      [49, "ProjectionThreadLinkedPullRequest"],
      [50, "ProjectionThreadsUnsettledAt"],
    ],
  },
  {
    source: "lastcode/build/v0.0.37-nightly.20260830.1232.1.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ProjectionThreadAnnotation"],
      [45, "UpdateDrain"],
      [46, "UpdateDrainClaim"],
      [47, "ProjectionTurnRequestCorrelations"],
      [48, "ProjectionThreadWorktreeCleanup"],
      [49, "ProjectionThreadLinkedPullRequest"],
      [50, "ProjectionThreadsUnsettledAt"],
      [51, "ProjectionThreadMessageSource"],
    ],
  },
  {
    source: "lastcode/build/v0.0.38-nightly.20260901.1243.1.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ProjectionThreadAnnotation"],
      [45, "UpdateDrain"],
      [46, "UpdateDrainClaim"],
      [47, "ProjectionTurnRequestCorrelations"],
      [48, "ProjectionThreadWorktreeCleanup"],
      [49, "ProjectionThreadLinkedPullRequest"],
      [50, "ProjectionThreadsUnsettledAt"],
      [51, "ProjectionThreadMessageSource"],
      [52, "ProjectionThreadsPersistent"],
    ],
  },
  {
    source: "lastcode/build/v0.0.39-nightly.20260903.1267.3.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ClearAutomaticProjectModelDefaults"],
      [45, "ProjectionProjectsAutoPull"],
      [46, "RepairAutomaticSettlementTimestamps"],
      [47, "ProjectionProjectIcon"],
      [48, "ProjectionThreadAnnotation"],
      [49, "UpdateDrain"],
      [50, "UpdateDrainClaim"],
      [51, "ProjectionTurnRequestCorrelations"],
      [52, "ProjectionThreadWorktreeCleanup"],
      [53, "ProjectionThreadLinkedPullRequest"],
      [54, "ProjectionThreadsUnsettledAt"],
      [55, "ProjectionThreadMessageSource"],
      [56, "ProjectionThreadsPersistent"],
    ],
  },
  {
    source: "lastcode/build/v0.0.39-nightly.20260903.1267.4.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ClearAutomaticProjectModelDefaults"],
      [45, "ProjectionProjectsAutoPull"],
      [46, "RepairAutomaticSettlementTimestamps"],
      [47, "ProjectionProjectIcon"],
      [48, "ProjectionThreadAnnotation"],
      [49, "UpdateDrain"],
      [50, "UpdateDrainClaim"],
      [51, "ProjectionTurnRequestCorrelations"],
      [52, "ProjectionThreadWorktreeCleanup"],
      [53, "ProjectionThreadLinkedPullRequest"],
      [54, "ProjectionThreadsUnsettledAt"],
      [55, "ProjectionThreadMessageSource"],
      [56, "ProjectionThreadsPersistent"],
      [57, "ProjectionProjectIcon"],
    ],
  },
  {
    source: "lastcode/build/v0.0.39-nightly.20260904.1276.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ClearAutomaticProjectModelDefaults"],
      [45, "ProjectionProjectsAutoPull"],
      [46, "RepairAutomaticSettlementTimestamps"],
      [47, "ProjectionProjectIcon"],
      [48, "ProjectionThreadAnnotation"],
      [49, "UpdateDrain"],
      [50, "UpdateDrainClaim"],
      [51, "ProjectionTurnRequestCorrelations"],
      [52, "ProjectionThreadWorktreeCleanup"],
      [53, "ProjectionThreadLinkedPullRequest"],
      [54, "ProjectionThreadsUnsettledAt"],
      [55, "ProjectionThreadMessageSource"],
      [56, "ProjectionThreadsPersistent"],
      [57, "ProjectionThreadAttention"],
    ],
  },
  {
    source: "lastcode/build/v0.0.39-nightly.20260904.1276.1.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ClearAutomaticProjectModelDefaults"],
      [45, "ProjectionProjectsAutoPull"],
      [46, "RepairAutomaticSettlementTimestamps"],
      [47, "ProjectionProjectIcon"],
      [48, "ProjectionThreadAnnotation"],
      [49, "UpdateDrain"],
      [50, "UpdateDrainClaim"],
      [51, "ProjectionTurnRequestCorrelations"],
      [52, "ProjectionThreadWorktreeCleanup"],
      [53, "ProjectionThreadLinkedPullRequest"],
      [54, "ProjectionThreadsUnsettledAt"],
      [55, "ProjectionThreadMessageSource"],
      [56, "ProjectionThreadsPersistent"],
      [57, "ProjectionThreadAttention"],
      [58, "RepairMigration57ProjectionColumns"],
    ],
  },
  {
    source: "lastcode/build/v0.0.39-nightly.20260907.1325.1",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ClearAutomaticProjectModelDefaults"],
      [45, "ProjectionProjectsAutoPull"],
      [46, "RepairAutomaticSettlementTimestamps"],
      [47, "ProjectionProjectIcon"],
      [48, "ProjectionThreadAnnotation"],
      [49, "UpdateDrain"],
      [50, "UpdateDrainClaim"],
      [51, "ProjectionTurnRequestCorrelations"],
      [52, "ProjectionThreadWorktreeCleanup"],
      [53, "ProjectionThreadLinkedPullRequest"],
      [54, "ProjectionThreadsUnsettledAt"],
      [55, "ProjectionThreadMessageSource"],
      [56, "ProjectionThreadsPersistent"],
      [57, "ProjectionThreadAttention"],
      [58, "ProjectionThreadBranchPullRequest"],
      [59, "ProjectionThreadsActiveOrderKey"],
    ],
  },
  {
    source: "lastcode/checkpoint/v0.0.34-nightly.20260822.1157",
    entries: [[42, "ProjectionThreadAnnotation"]],
  },
  {
    source: "lastcode/checkpoint/v0.0.34-nightly.20260822.1159",
    entries: [
      [42, "ProjectionThreadAnnotation"],
      [43, "UpdateDrain"],
    ],
  },
  {
    source: "lastcode/checkpoint/v0.0.34-nightly.20260825.1182",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadAnnotation"],
      [44, "UpdateDrain"],
      [45, "UpdateDrainClaim"],
      [46, "ProjectionTurnRequestCorrelations"],
      [47, "ProjectionThreadWorktreeCleanup"],
    ],
  },
  {
    source: "lastcode/checkpoint/v0.0.39-nightly.20260902.1256",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ProjectionThreadAnnotation"],
      [45, "UpdateDrain"],
      [46, "UpdateDrainClaim"],
      [47, "ProjectionTurnRequestCorrelations"],
      [48, "ProjectionThreadWorktreeCleanup"],
      [49, "ProjectionThreadLinkedPullRequest"],
      [50, "ProjectionThreadsUnsettledAt"],
      [51, "ProjectionThreadMessageSource"],
      [52, "ProjectionThreadsPersistent"],
      [53, "ClearAutomaticProjectModelDefaults"],
    ],
  },
  {
    source: "lastcode/checkpoint/v0.0.39-nightly.20260903.1262",
    entries: [
      [42, "ProjectionThreadLinkedPullRequest"],
      [43, "ProjectionThreadsUnsettledAt"],
      [44, "ProjectionThreadAnnotation"],
      [45, "UpdateDrain"],
      [46, "UpdateDrainClaim"],
      [47, "ProjectionTurnRequestCorrelations"],
      [48, "ProjectionThreadWorktreeCleanup"],
      [49, "ProjectionThreadLinkedPullRequest"],
      [50, "ProjectionThreadsUnsettledAt"],
      [51, "ProjectionThreadMessageSource"],
      [52, "ProjectionThreadsPersistent"],
      [53, "ClearAutomaticProjectModelDefaults"],
      [54, "ProjectionProjectsAutoPull"],
      [55, "RepairAutomaticSettlementTimestamps"],
    ],
  },
] as const;
